<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PositiveHttp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(ControlRoot)solutions/Api.cs" />
    <Compile Include="$(ControlRoot)../../../tasks/aspnetcore/tests/Contract.cs" />
    <Compile Include="$(ControlRoot)../../../tasks/aspnetcore/tests/AspnetcoreTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.11" />
  </ItemGroup>
</Project>
