module FunnySharp.Harness.Tests.PerformanceTests

open System
open System.IO
open System.Text.Json
open System.Text.Json.Nodes
open Xunit
open FunnySharp.Harness.Performance
open FunnySharp.Harness.Tests.Support

let private present (node: JsonNode | null) =
    match node with
    | null -> failwith "Missing fixture node"
    | value -> value

let private parse text = JsonNode.Parse(text: string) |> present
let private field (node: JsonNode) (name: string) = present node.[name]

let private withFixture action =
    use temp = new TempDirectory()
    let git args =
        let result = FunnySharp.Harness.Proc.runCaptureIn (Some temp.Path) "git" args |> Async.RunSynchronously
        Assert.Equal(0, result.ExitCode)
        result.Stdout.Trim()
    git [ "init" ] |> ignore
    let sourcePath = Path.Combine(temp.Path, "Source.cs")
    File.WriteAllText(sourcePath, "// committed benchmark source")
    git [ "add"; "Source.cs" ] |> ignore
    git [ "-c"; "user.name=Fixture"; "-c"; "user.email=fixture@example.invalid"; "commit"; "-m"; "fixture" ] |> ignore
    let commit = git [ "rev-parse"; "HEAD" ]
    let rows = parse """[{"id":"Fixture|Category|Direct|","benchmarkClass":"Fixture","category":"Category","method":"Direct","parameters":"","baseline":true,"carrier":"value","completionPath":"synchronous","expectedResult":"42","comparisonGroup":"fixture","included":true,"exclusionReason":null,"allocationBudgetBytes":0},{"id":"Fixture|Category|Funny|","benchmarkClass":"Fixture","category":"Category","method":"Funny","parameters":"","baseline":false,"carrier":"value","completionPath":"synchronous","expectedResult":"42","comparisonGroup":"fixture","included":true,"exclusionReason":null,"allocationBudgetBytes":16}]"""
    let manifest = JsonObject()
    manifest.["schemaVersion"] <- JsonValue.Create 1
    manifest.["policy"] <- parse """{"revision":"fixture-v1"}"""
    (field manifest "policy").["rows"] <- rows
    let excluded = parse """{"id":"excluded|fixture","benchmarkClass":"Fixture","category":"Excluded","method":"","parameters":"","baseline":false,"carrier":"unmeasured","completionPath":"unmeasured","expectedResult":"unmeasured","comparisonGroup":"unmeasured","included":false,"exclusionReason":"Outside measured scenarios","allocationBudgetBytes":null}"""
    rows.AsArray().Add excluded
    let preflight = parse """{"schemaVersion":1,"runId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","completedAtUtc":"2026-01-01T00:00:00Z","policyRevision":"fixture-v1","runtime":".NET 10","semanticCases":["Fixture|"],"excludedIds":["excluded|fixture"]}"""
    preflight.["candidateCommit"] <- JsonValue.Create commit
    let checkedRows = rows.DeepClone()
    checkedRows.AsArray().RemoveAt 2
    for row in checkedRows.AsArray() do (present row).["semanticsChecked"] <- JsonValue.Create true
    preflight.["rows"] <- checkedRows
    let child = parse """{"runId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","capturedAtUtc":"2026-01-01T00:00:01Z","processId":1,"runtime":".NET 10","benchmarkClass":"Fixture","parameters":"","workloadAssembly":"BenchmarkDotNet.Autogenerated"}"""
    child.["candidateCommit"] <- JsonValue.Create commit
    let receipt = parse """{"schemaVersion":1,"succeeded":true,"generatedAtUtc":"2026-01-01T00:00:02Z","policyRevision":"fixture-v1","environment":{"os":"fixture","architecture":"X64","sdkVersion":"10.0.400","runtime":".NET 10","jit":"RyuJIT","gcServer":false,"gcConcurrent":true,"gcAllocationQuantum":8},"reports":[{"file":"FunnySharp.Benchmarks.Fixture-report.csv"},{"file":"FunnySharp.Benchmarks.Fixture-report-github.md"},{"file":"FunnySharp.Benchmarks.Fixture-report.html"}],"binding":{"preflight":{"file":"preflight.json"},"launches":[{"rowId":"Fixture|Category|Direct|","file":"direct.log"},{"rowId":"Fixture|Category|Funny|","file":"funny.log"}]}}"""
    receipt.["candidateCommit"] <- JsonValue.Create commit
    let observed = rows.DeepClone()
    observed.AsArray().RemoveAt 2
    for row in observed.AsArray() do
        let row = present row
        row.["timingState"] <- JsonValue.Create "unavailable"
        row.["meanNanoseconds"] <- null
        row.["allocatedBytesPerOperation"] <- (field row "allocationBudgetBytes").DeepClone()
    receipt.["rows"] <- observed
    let manifestPath = Path.Combine(temp.Path, "manifest.json")
    let receiptPath = Path.Combine(temp.Path, "Fixture-performance-receipt.json")
    let write () =
        File.WriteAllText(manifestPath, manifest.ToJsonString())
        File.WriteAllText(receiptPath, receipt.ToJsonString())
        File.WriteAllText(Path.Combine(temp.Path, "preflight.json"), preflight.ToJsonString())
        let marker = "// funnysharp-workload:" + Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(child.ToJsonString()))
        for name in [ "direct.log"; "funny.log" ] do File.WriteAllText(Path.Combine(temp.Path, name), marker)
        for report in (field receipt "reports").AsArray() do
            File.WriteAllText(Path.Combine(temp.Path, (field (present report) "file").GetValue<string>()), "BenchmarkDotNet report")
    let run () =
        write ()
        FunnySharp.Harness.Performance.run temp.Path manifestPath temp.Path None
    let changeSource staged =
        File.WriteAllText(sourcePath, "// changed benchmark source")
        if staged then git [ "add"; "Source.cs" ] |> ignore
    action receipt preflight child run changeSource

[<Fact>]
let ValidMeasurementWithUnavailableTimingPasses () =
    withFixture (fun _ _ _ run _ ->
        match run () with
        | Ok _ -> ()
        | Error error -> failwith error.Message)

[<Theory>]
[<InlineData(false)>]
[<InlineData(true)>]
let TrackedSourceEditFailsWithUnchangedHead staged =
    withFixture (fun _ _ _ run changeSource ->
        match run () with
        | Ok _ -> ()
        | Error error -> failwith error.Message
        changeSource staged
        match run () with
        | Ok _ -> failwith "Dirty tracked source passed performance verification"
        | Error error -> Assert.Contains("clean tracked Git", error.Message))

[<Theory>]
[<InlineData("allocation")>]
[<InlineData("fractional")>]
[<InlineData("negative")>]
[<InlineData("duplicate")>]
[<InlineData("unexpected")>]
[<InlineData("excluded")>]
[<InlineData("runtime")>]
[<InlineData("unsuccessful")>]
[<InlineData("missing-row")>]
[<InlineData("missing-launch")>]
[<InlineData("semantics")>]
[<InlineData("wrong-run")>]
[<InlineData("wrong-source")>]
[<InlineData("environment")>]
let InvalidMeasurementFails kind =
    withFixture (fun receipt preflight child run _ ->
        match kind with
        | "allocation" -> (present (field receipt "rows").[1]).["allocatedBytesPerOperation"] <- JsonValue.Create 17
        | "fractional" -> (present (field receipt "rows").[1]).["allocatedBytesPerOperation"] <- JsonValue.Create 1.5
        | "negative" -> (present (field receipt "rows").[1]).["allocatedBytesPerOperation"] <- JsonValue.Create -1
        | "duplicate" -> (field receipt "rows").AsArray().Add((present (field receipt "rows").[0]).DeepClone())
        | "unexpected" -> (present (field receipt "rows").[1]).["id"] <- JsonValue.Create "unknown"
        | "excluded" -> (present (field receipt "rows").[1]).["id"] <- JsonValue.Create "excluded|fixture"
        | "runtime" -> child.["runtime"] <- JsonValue.Create ".NET other"
        | "unsuccessful" -> receipt.["succeeded"] <- JsonValue.Create false
        | "missing-row" -> (field receipt "rows").AsArray().RemoveAt 1
        | "missing-launch" -> (field (field receipt "binding") "launches").AsArray().RemoveAt 1
        | "semantics" -> (present (field preflight "rows").[1]).["semanticsChecked"] <- JsonValue.Create false
        | "wrong-run" -> child.["runId"] <- JsonValue.Create "other"
        | "wrong-source" -> receipt.["candidateCommit"] <- JsonValue.Create "other"
        | "environment" -> (field receipt "environment").AsObject().Remove "runtime" |> ignore
        | _ -> failwith "Unknown case"
        match run () with
        | Ok _ -> failwith "Invalid measurement passed"
        | Error _ -> ())
