<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LastWinner</AssemblyName>
    <DefineConstants>$(DefineConstants);LAST_WINNER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(ControlRoot)solutions/AvailabilityCoordinator.cs" />
    <Compile Include="$(ControlRoot)../tasks/concurrency/tests/Contract.cs" />
    <Compile Include="$(ControlRoot)../tasks/concurrency/tests/ConcurrencyTests.cs" />
  </ItemGroup>
</Project>
